### ISSUE TITLE
Celebrate first time contributor merges

### ISSUE THREAD

**Issue by PierreRochard** [PierreRochard/github-twitter#4]

**Comment by PierreRochard** [comment]
https://twitter.com/jfnewbery/status/913037582916874242

**Comment by PierreRochard** [comment]
Found that we can only get 100 contributors through the github api. https://stackoverflow.com/questions/18148490/how-can-i-get-more-than-100-results-from-github-api-v3-using-github-api-gem

Will experiment with GitPython querying the actual git repo as a workaround

**Comment by jnewbery** [comment]
Query the commits in the repo, filtering by author: https://developer.github.com/v3/repos/commits/

**Comment by PierreRochard** [comment]
@jnewbery that's perfect!
